server:
  address: localhost
  port: 8680
  servlet:
    context-path: /api
  error:
    include-message: always
  tomcat:
    accesslog:
      enabled: true
      request-attributes-enabled: true

spring:
  application:
    name: y-a-foot-users-admin
  profiles:
    active: ${spring.profile}
  security:
    user:
      name: ${security.api.username}
      password: ${security.api.password}
      roles: ADMINISTRATOR

# Application configuration
app:
  web:
    public:
      url: ${web.app.public.url}
      password-reset:
        url: dummy
  keycloak:
    server:
      url: ${keycloak.server.url}
      realm: ${keycloak.server.realm}
    client:
      id: ${keycloak.client.id}
      secret: ${keycloak.client.secret}
      username: ${keycloak.client.username}
      password: ${keycloak.client.password}
  security:
    jwt:
      token:
        secret: dummy
        active:
          minutes: 0

# REST API
api:
  config:
    rest:
      allowed-origin: ${rest.api.allowed.url}
      logging:
        include:
          headers: ${rest.logging.include.headers}
          query: ${rest.logging.include.query}
          payload: ${rest.logging.include.payload}
        max-payload-length: ${rest.logging.max.payload.length}
    public:
      url: ${rest.api.public.url}
  users:
    root:
      path: /users
    one:
      path: ${api.users.root.path}/{0}