openapi: 3.0.2

info:
  title: Y'a foot - Users Administration
  description: Y'a foot Users Registration REST API
  version: 2.0.0

servers:
  - url: http://localhost:8680/api
    description: Localhost deployment

tags:
  - name: users
    description: Users management API. It allows to create, update and delete users

paths:
  /users/{email}:
    parameters:
      - in: path
        name: email
        required: true
        schema:
          type: string
          format: email
        description: Email address identifying the user
    delete:
      operationId: deleteUser
      summary: Deletes a given a user
      tags:
        - users
      responses:
        204: # No content
          description: User successfully deleted
        403: # Forbidden
          description: User not allowed to perform this operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404: # Not found
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500: # Internal server error
          description: An error occurred while looking for user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    User:
      type: object
      required:
        - first_name
      properties:
        email:
          type: string
          format: email
        first_name:
          type: string
          pattern: ^[A-Za-z0-9äáàéèëêïíôóöòúûùüÄÁÀÉÈËÊÏÍÔÓÒÚÛÙÜçÇñÑ\'\-]{1,255}$
        surname:
          type: string
          pattern: ^[A-Za-z0-9äáàéèëêïíôóöòúûùüÄÁÀÉÈËÊÏÍÔÓÒÚÛÙÜçÇñÑ\'\-]{1,255}$

    ErrorResponse:
      type: object
      required:
        - timestamp
        - error
        - message
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
          format: uri
