ALTER TABLE t_match ALTER COLUMN mat_covoiturage_actif DROP DEFAULT;
ALTER TABLE t_match ALTER COLUMN mat_partage_actif DROP DEFAULT;
ALTER TABLE t_match ALTER COLUMN mat_date TYPE TIMESTAMP WITH TIME ZONE;
