server:
  address: localhost
  port: 8580
  servlet:
    context-path: /api
  error:
    include-message: always
  tomcat:
    accesslog:
      enabled: true
      request-attributes-enabled: true

spring:
  application:
    name: y-a-foot-users-auth
  profiles:
    active: ${spring.profile}
  ldap:
    urls: ${ldap.url}
    username: ${ldap.dn}
    password: ${ldap.password}
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: ${mail.smtp.auth}
          starttls:
            enable: ${mail.smtp.starttls.enable}
            required: ${mail.smtp.starttls.required}
  freemarker:
    enabled: true
    content-type: text/plain

app:
  ldap:
    config:
      users:
        dn: ${ldap.users.dn}
      roles:
        dn: ${ldap.roles.dn}
  security:
    jwt:
      token:
        secret: ${security.jwt.token.secret}
        active:
          minutes: 60
  mail:
    sender:
      address: ${mail.sender.address}
      name: ${mail.sender.name}
  web:
    public:
      url: ${web.app.public.url}
      password-reset:
        url: ${app.web.public.url}/password-reset?token={0}

api:
  rest:
    logging:
      include:
        headers: ${rest.logging.include.headers}
        query: ${rest.logging.include.query}
        payload: ${rest.logging.include.payload}
      max-payload-length: ${rest.logging.max.payload.length}
  public:
    url: ${rest.api.public.url}
  security:
    jwt:
      token:
        active:
          minutes: 60
  users:
    path: /users